[package]
edition = "2024"
name = "unigraph_ingestion"
publish = false
version = "0.0.0"

[dependencies]
anyhow = "1"
unigraph_cargo = { path = "../unigraph_cargo" }
unigraph_core = { path = "../unigraph_core" }
unigraph_git = { path = "../unigraph_git" }
unigraph_db = { path = "../unigraph_db" }
unigraph_storage_core = { path = "../unigraph_storage_core" }
unigraph_timestamp = { path = "../unigraph_timestamp" }
