// Copyright (c) Meta Platforms, Inc. and affiliates.

#![allow(clippy::collapsible_if)]
#![allow(clippy::collapsible_else_if)]
#![feature(once_cell_try)]
mod array_graph_serializable;
pub mod config_key;
pub mod config_query;
pub mod identifiers;
pub mod map_graph_builder;
pub mod metric_view;
mod test_graph;
pub(crate) mod traversal;
pub mod types;

pub use crate::array_graph_serializable::ArrayGraphSerializable;
pub use crate::array_graph_serializable::ArrayGraphSerializableEdges;
pub use crate::array_graph_serializable::ArrayGraphSerializableNodeMetadata;
pub use crate::array_graph_serializable::delta::GraphDelta;
pub use crate::array_graph_serializable::delta::GraphSettingsDelta;
pub use crate::array_graph_serializable::delta::TraversalConfigDelta;
pub use crate::array_graph_serializable::delta::apply_delta;
pub use crate::array_graph_serializable::delta::apply_deltas;
pub use crate::array_graph_serializable::delta::derive_delta;
pub use crate::array_graph_serializable::delta::package::DeltaManifest;
pub use crate::array_graph_serializable::delta::package::DeltaManifestStats;
pub use crate::array_graph_serializable::delta::package::DeltaPackage;
pub use crate::array_graph_serializable::delta::package::pack_delta;
pub use crate::array_graph_serializable::delta::package::unpack_delta;
pub use crate::array_graph_serializable::error_package::ErrorManifest;
pub use crate::array_graph_serializable::error_package::ErrorManifestStats;
pub use crate::array_graph_serializable::error_package::ErrorPackage;
pub use crate::array_graph_serializable::error_package::pack_errors;
pub use crate::array_graph_serializable::error_package::unpack_errors;
pub use crate::array_graph_serializable::package::ArrayGraphSerializableManifest;
pub use crate::array_graph_serializable::package::ArrayGraphSerializablePackage;
pub use crate::array_graph_serializable::package::ArrayGraphSerializablePackageBase64;
pub use crate::array_graph_serializable::package::ArrayGraphSerializablePackageConfig;
pub use crate::array_graph_serializable::package::BlobID;
pub use crate::array_graph_serializable::package::ManifestBlobs;
pub use crate::array_graph_serializable::package::ManifestStats;
pub use crate::array_graph_serializable::package::from_blobs_json;
pub use crate::array_graph_serializable::package::into_blobs_json;
pub use crate::config_key::ConfigKeyLike;
pub use crate::config_key::ConfigRow;
pub use crate::config_key::GraphQueryConfigKey;
pub use crate::config_key::TraversalConfigKey;
pub use crate::config_query::GraphQueryConfig;
pub use crate::identifiers::GraphID;
pub use crate::identifiers::GraphKey;
pub use crate::identifiers::GraphTimeKey;
pub use crate::identifiers::TimelineID;
pub use crate::identifiers::Timestamp;
pub use crate::map_graph_builder::GraphBuilder;
pub use crate::metric_view::MetricView;
pub use crate::test_graph::make_test_graph;
pub use crate::traversal::Decision;
pub use crate::traversal::DefaultBranches;
pub use crate::traversal::DynamicEdgeOverride;
pub use crate::traversal::DynamicTypeConfig;
pub use crate::traversal::NodeLabelPredicate;
pub use crate::traversal::TraversalConfig;
pub use crate::traversal::messages::Message;
pub use crate::traversal::tiered_traversal::AscendingTier;
pub use crate::traversal::tiered_traversal::AscendingTiersConfig;
pub use crate::traversal::tiered_traversal::TieredTraversalConfig;
pub use crate::types::NodeIDX;
pub use crate::types::array_graph::ArrayGraph;
pub use crate::types::array_graph::ArrayGraphDynamicEdge;
pub use crate::types::array_graph::Arrow;
pub use crate::types::array_graph::DynamicEdgeInfo;
pub use crate::types::array_graph::array_graph_debug_utils::ArrayGraphDebugUtils;
pub use crate::types::array_graph::array_graph_metrics::CombinedMetricsForNodes;
pub use crate::types::array_graph::array_graph_nodes::ArrayGraphNodes;
pub use crate::types::array_graph::array_graph_nodes::GraphSide;
pub use crate::types::array_graph::array_graph_stats::ArrayGraphStats;
pub use crate::types::array_graph::graph_settings;
pub use crate::types::array_graph::graph_settings::GraphSettings;
pub use crate::types::array_graph::offset_graph::NonDirectedEdgeMetadata;
pub use crate::types::array_graph::offset_graph::TraversalType;
pub use crate::types::array_graph::remap_utils;
pub use crate::types::map_graph::MapGraph;
pub use crate::types::twin_graph::TwinGraph;
pub use crate::types::twin_graph::get_arrows::TwinArrow;
pub use crate::types::ui_types;
#[cfg(test)]
mod tests;
