[typescript]
export_path = "u-fe/__generated__/ts"
header = """
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * @generated
 */
"""

[flow]
export_path = "../../../www/html/intern/js/unigraph/__generated__/typegen"
file_name_prefix = "UnigraphTypeGen"
header = """
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * @oncall unigraph
 * @flow
 * @generated
 * @codegen-command: cd ~/fbsource/fbcode && buck test //unigraph/oss/... -- --env TYPEGEN=1
 */
"""

[hack]
export_path = "../../../www/flib/intern/unigraph/__generated__/typegen"
type_name_prefix = "TUnigraph"
file_name_prefix = "UnigraphTypeGen"
header = """
<?hh

/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * @flow
 * @generated
 * @codegen-command: cd ~/fbsource/fbcode && buck test //unigraph/oss/... -- --env TYPEGEN=1
 */

<<Oncalls('unigraph')>>
"""
