/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * @generated
 */


/**
 * Structured RPC error, usable in any transport's output enum.
 * Every `{Name}Response` generated by [`define_rpc!`] includes an
 * `Error(RpcError)` variant for structured error propagation.
 */
export interface RpcError {
  display: string;
  debug?: string | undefined;
}