// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum that defines how the graph structure is displayed in the UI.
 * e.g. which edges we will be following when visualizing the
 * graph in the tree table.
 */
export type ArrayGraphUISettingsGraphStructure = "Forward" | "Dominator" | "Reverse";
