// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArrayGraphStats = { num_all_nodes: number, num_all_edges: number, num_directed_edges: number, num_tagged_edges: number, num_dynamic_edges: number, tier_names: Array<string>, };
