// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArrayGraphUISettingsGraphStructure } from "./ArrayGraphUISettingsGraphStructure";
import type { ArrayGraphUISettingsTreeTableEntryPoints } from "./ArrayGraphUISettingsTreeTableEntryPoints";
import type { ColumnSettings } from "./ColumnSettings";
import type { GraphTableSort } from "./GraphTableSort";
import type { SidebarPanel } from "./SidebarPanel";

export type ArrayGraphUISettings = { selected_sidebar_panel?: SidebarPanel, graph_table_sort?: GraphTableSort, columns?: ColumnSettings, graph_structure?: ArrayGraphUISettingsGraphStructure, entry_points?: ArrayGraphUISettingsTreeTableEntryPoints, 
/**
 * Used in combination with `entry_points` settings.`
 * If entry_points is set to `Specified`, this value will be
 * used to determine entry points. This value is stored separately
 * so we can preserve selected entry points when switching
 * between different entry points settings.
 * E.g. if we're exploring `reverse from a specific node` and want
 * to hop into `show as flat list`, we want to preserve
 * the selected entry points, so when we switch back to "reverse"
 * we keep the same selected entry point
 */
entry_points_specified?: Array<string>, };
