// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeIDX } from "./NodeIDX";

/**
 * This is a more heavyweight struct describing an edge in the graph.
 * This can represent any edge (directed/tagged/dynamic).
 * This is meant to be used for more sparce operations, like rendering
 * edges in the UI, or for debugging. Since these are much heavier they
 * are not fit for heavy computations, like DFS/BFS, computing transitive
 * metrics, etc.
 */
export type Arrow = { tag: string | null, branch: string | null, properties: { [key in string]?: string } | null, points_from: NodeIDX, points_to: NodeIDX, excluded: boolean, };
