// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AscendingTier } from "./AscendingTier";

export type AscendingTiersConfig = { tiers: Array<AscendingTier>, 
/**
 * If this is set, the traversal will stop at this tier
 * and not traverse any further.
 */
max_tier: number | null, };
