// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AscendingTier = { name: string, tags_that_transition_to_this_tier: Array<string>, };
