// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndividualOptionEnabled } from "./IndividualOptionEnabled";

export type ColumnSettings = { show_parents_count?: boolean, show_transitive_count?: IndividualOptionEnabled, show_conjoint_count?: IndividualOptionEnabled, 
/**
 * Global setting for showing tiered values for metrics
 * (if tiers are defined)
 * It is shown by default, but can be hidden
 */
hide_tiered?: boolean, 
/**
 * Global setting for showing transitive values.
 * Individual columns will be enabled/disabled based on
 * their individual settings.
 */
show_transitive?: boolean, 
/**
 * Global setting for showing conjoint cost values.
 * Individual columns will be enabled/disabled based on
 * their individual settings.
 */
show_conjoint?: boolean, };
