// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndividualOptionEnabled } from "./IndividualOptionEnabled";

export type ColumnSettings = { show_parents_count?: boolean, show_transitive_count?: IndividualOptionEnabled, show_conjoint_count?: IndividualOptionEnabled, 
/**
 * Global setting for showing tiered values for metrics
 * (if tiers are defined)
 */
show_tiered?: boolean, };
