// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents values for metrics for a set of nodes.
 * Not transitive, just aggregated for things like
 * "give me total size of all the nodes i just selected"
 */
export type CombinedMetricsForNodes = { metrics: { [key in string]?: number }, tiered_metrics: { [key in string]?: { [key in string]?: number } }, node_count: number, };
