// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";

export type ForceDynamic = { from_node: string | null, match_properties: { [key in string]?: string }, branch: string | null, decision: Decision, };
