// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArrayGraphUISettings } from "./ArrayGraphUISettings";
import type { MetricSettings } from "./MetricSettings";

export type GraphSettings = { metric_settings?: { [key in string]?: MetricSettings }, ui_settings?: ArrayGraphUISettings, };
