// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortOrder } from "./SortOrder";

export type GraphTableSort = { column_id: string, order: SortOrder, };
