// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricFormat } from "./MetricFormat";

export type MetricSettings = { description?: string, format?: MetricFormat, 
/**
 * Hide table column that displays the metric itself.
 */
column_hide_self?: boolean, 
/**
 * hide the column that displays transitive value for the metric.
 */
column_hide_transitive?: boolean, 
/**
 * Hide columns that display transitive tiered value for provided tier names.
 */
column_hide_trantitive_tiered?: Array<string>, show_conjoint_self?: boolean, show_conjoint_tiered?: Array<string>, };
