// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SizeConfig } from "./SizeConfig";

/**
 * Value that defines how to format metric values (in the UI or CLI output)
 * This value is cross platform enum type which is represented as an object/shape
 * with all keys/properties optional and expected to have exactly ONE key/property
 * to be set at runtime.
 */
export type MetricFormat = { "Percent": { 
/**
 * If set to true, the value is expected to be divided by 100.
 * e.g. 0 => 0%, 1.0 => 100%, 0.24 => 24%
 */
scaled_percentage: boolean | null, } } | { "SizeBytes": { 
/**
 * Configures the unit format for the size metric, units can be variable or forced (kB/MB/GB)
 */
config: SizeConfig | null, } } | { "NumericBoolean": Record<string, never> } | { "NumberWithVariablePrecision": { min_precision: number | null, max_precision: number | null, use_delimiter: boolean | null, } };
