// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndividualOptionEnabled } from "./IndividualOptionEnabled";
import type { MetricFormat } from "./MetricFormat";

export type MetricSettings = { description?: string, format?: MetricFormat, 
/**
 * Hide table column that displays the metric itself.
 */
column_hide_self?: boolean, 
/**
 * Column that displays transitive value for the metric.
 */
column_show_transitive?: IndividualOptionEnabled, column_show_tiered?: { [key in string]?: IndividualOptionEnabled }, show_conjoint_self?: IndividualOptionEnabled, show_conjoint_tiered?: { [key in string]?: IndividualOptionEnabled }, };
