// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for size formatting
 */
export type SizeConfig = { "VariableUnits": Record<string, never> } | { "ForcekB": Record<string, never> } | { "ForceMB": Record<string, never> } | { "ForceGB": Record<string, never> } | { "ForceKiB": Record<string, never> } | { "ForceMiB": Record<string, never> } | { "ForceGiB": Record<string, never> };
