// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";
import type { ForceDynamic } from "./ForceDynamic";
import type { NodeTagSetsPredicate } from "./NodeTagSetsPredicate";
import type { TieredTraversalConfig } from "./TieredTraversalConfig";

export type TraversalConfig = { force_nodes: { [key in string]?: Decision }, 
/**
 * From Node Name -> To Node Name -> Decision
 */
force_edges: { [key in string]?: { [key in string]?: Decision } }, 
/**
 * These rules are ordered. The first one that matches will be used.
 */
tag_sets: Array<NodeTagSetsPredicate>, 
/**
 * These rules are ordered. The first one that matches will be used.
 */
force_dynamic: Array<ForceDynamic>, tiered_traversal: TieredTraversalConfig | null, };
