// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";

export type TraversalConfig = { force_nodes: { [key in string]?: Decision }, force_edges: { [key in string]?: { [key in string]?: Decision } }, };
