// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectionType } from "./SelectionType";
import type { TsVec2 } from "./TsVec2";

export type Selection = { selection_from_point: TsVec2, selection_to_point: TsVec2, selection_type: SelectionType, };
