// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimulationColors = { background: [number, number, number], node_main: [number, number, number], node_selected: [number, number, number], };
