// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Selection } from "./Selection";
import type { SimulationColors } from "./SimulationColors";

export type SimulationParams = { active: boolean, render_edges: boolean, node_size_scale: number, gravity_force_multiplier: number, edge_force_multiplier: number, max_velocity_multiplier: number, selection: Selection, colors: SimulationColors, };
